const APP_DATA = {
  sections: [
    {
      id: 'A', name: 'AI Tools & General Literacy', icon: '🤖',
      questions: [
        {id: 'a1', text: 'I can explain what Generative AI (e.g. ChatGPT, Gemini) does in simple terms'},
        {id: 'a2', text: 'I have used an AI tool (chatbot, image generator, AI assistant) in the last 30 days'},
        {id: 'a3', text: 'I can write an effective prompt to get a useful AI response'},
        {id: 'a4', text: 'I understand the difference between AI-generated and human-created content'},
        {id: 'a5', text: 'I am aware of at least 3 AI tools relevant to police / govt work'},
      ]
    },
    {
      id: 'B', name: 'Cybersecurity & AI Threats', icon: '🔐',
      questions: [
        {id: 'b1', text: 'I can identify common cyber threats (phishing, deepfakes, AI-generated scams)'},
        {id: 'b2', text: 'I know how AI is being used by cybercriminals today'},
        {id: 'b3', text: 'I am aware of deepfake technology and its misuse potential'},
        {id: 'b4', text: 'My team has protocols to verify AI-generated or suspicious digital content'},
        {id: 'b5', text: 'I follow data hygiene practices (strong passwords, 2FA, encrypted comms)'},
      ]
    },
    {
      id: 'C', name: 'Communication & Data Analytics', icon: '📡',
      questions: [
        {id: 'c1', text: 'I can use AI to summarise or translate documents quickly'},
        {id: 'c2', text: 'I am comfortable working with data (spreadsheets, dashboards, reports)'},
        {id: 'c3', text: 'I can use AI tools to draft official communications or reports'},
        {id: 'c4', text: 'I can interpret basic crime data / statistics to support decisions'},
        {id: 'c5', text: 'I am aware of AI tools for real-time language translation / transcription'},
      ]
    },
    {
      id: 'D', name: 'CCTV & Surveillance AI', icon: '📷',
      questions: [
        {id: 'd1', text: 'I understand how AI-powered CCTV systems differ from traditional CCTV'},
        {id: 'd2', text: 'I am aware of facial recognition technology used in policing'},
        {id: 'd3', text: 'I know about AI tools for crowd management and public safety monitoring'},
        {id: 'd4', text: 'I understand the ethical / legal boundaries of AI surveillance'},
        {id: 'd5', text: 'My unit has or is exploring AI-based tools for field operations'},
      ]
    },
  ],
  tasks: {
    A_B_0: {task: "Watch: 'What is AI?' — 15-min explainer video and write 3 takeaways in your own words", resource: "YouTube: 'AI Explained in 15 Minutes' by TED-Ed", minutes: 30},
    A_B_1: {task: 'Try ChatGPT or Gemini: Ask it to summarise a recent UP Police press release', resource: 'chat.openai.com or gemini.google.com (free tier)', minutes: 25},
    A_B_2: {task: "Read: 'AI for Beginners' — Chapter 1 (Microsoft free course)", resource: 'microsoft.com/ai-for-beginners', minutes: 30},
    A_B_3: {task: 'Practice: Write 5 prompts — ask AI to help draft an official notice', resource: 'ChatGPT / Gemini — save your best prompt', minutes: 25},
    A_B_4: {task: 'Quiz yourself: Can you explain AI to a colleague? Write a 3-sentence explanation', resource: 'Self-reflection + share in team WhatsApp group', minutes: 20},
    A_I_0: {task: 'Explore: Test 3 different AI tools (ChatGPT, Perplexity, Claude) on the same question', resource: 'chat.openai.com | perplexity.ai | claude.ai', minutes: 35},
    A_I_1: {task: 'Practice prompt engineering: Use role, context, format structure for a police report summary', resource: 'ChatGPT with the RCTF prompt framework (Role–Context–Task–Format)', minutes: 30},
    A_I_2: {task: 'Read: How Indian govt departments are using AI — 3 case studies', resource: 'NITI Aayog AI report (niti.gov.in) — free PDF', minutes: 30},
    A_I_3: {task: 'Build: Create a 5-prompt cheat sheet for your most common tasks', resource: 'Google Docs / Notepad — your personal prompt library', minutes: 30},
    A_I_4: {task: 'Share: Teach one AI tip to a colleague and note their reaction', resource: 'Peer learning — document in your 30-Day journal', minutes: 20},
    A_V_0: {task: 'Build a personal AI workflow: Map 3 daily tasks you can automate with AI', resource: 'Notion / Google Sheets — AI workflow map', minutes: 40},
    A_V_1: {task: 'Explore AI APIs: Use Gemini API to auto-summarise a document', resource: 'aistudio.google.com — free tier, no coding needed', minutes: 45},
    A_V_2: {task: "Lead: Run a 10-minute 'AI tip of the week' for your team", resource: 'Internal team meeting — prepare 1 slide or demo', minutes: 30},
    A_V_3: {task: 'Evaluate: Compare 5 AI tools on accuracy, privacy, and ease — write a 1-page note', resource: 'Side-by-side testing + Google Docs writeup', minutes: 45},
    A_V_4: {task: "Teach: Create a simple one-page 'AI Starter Guide' for new team members", resource: 'Canva (free) or Google Docs — shareable document', minutes: 40},
    B_B_0: {task: 'Learn: What is phishing? Watch a 10-min video and identify 3 red flags', resource: "YouTube: 'Phishing Explained' by Hak5", minutes: 25},
    B_B_1: {task: 'Read: What are deepfakes? Find 1 real example and note how it was detected', resource: "Google News search: 'deepfake police India 2024'", minutes: 25},
    B_B_2: {task: 'Practice: Test your password hygiene — use haveibeenpwned.com', resource: 'haveibeenpwned.com (free, no account needed)', minutes: 20},
    B_B_3: {task: 'Enable 2-factor authentication on your official work email/device', resource: 'Settings on your phone/computer — takes 5 mins', minutes: 15},
    B_B_4: {task: "Watch: 'How AI is used in cybercrime' — note 3 threats relevant to police", resource: 'YouTube: WIRED or Computerphile channel', minutes: 30},
    B_I_0: {task: 'Analyse: Find 1 recent UP cybercrime case — how could AI have helped prevent it?', resource: 'UP Police cybercrime portal + ChatGPT for analysis', minutes: 35},
    B_I_1: {task: "Practice: Use an AI tool to identify suspicious patterns in a sample email chain", resource: "ChatGPT: paste email, ask 'identify social engineering tactics'", minutes: 30},
    B_I_2: {task: 'Read: CERT-In guidelines on AI-related threats — summarise key points', resource: 'cert-in.org.in — free advisory downloads', minutes: 30},
    B_I_3: {task: 'Simulate: Run a mock phishing drill awareness session for 3 colleagues', resource: 'Sample phishing email templates — gophish.io (free)', minutes: 40},
    B_I_4: {task: 'Map: Create a visual of the 5 biggest AI-related cyber risks for UP Police', resource: 'Canva or Google Slides — 1 infographic', minutes: 35},
    B_V_0: {task: 'Lead: Brief your unit on deepfake detection — use 2 real video examples', resource: 'YouTube deepfake examples + InVID verification tool', minutes: 45},
    B_V_1: {task: 'Evaluate: Test 2 deepfake detection tools on sample media', resource: 'sensity.ai or Microsoft Video Authenticator', minutes: 40},
    B_V_2: {task: 'Contribute: Draft a 1-page SOP for handling suspected AI-generated evidence', resource: 'Word/Google Docs — submit to your supervisor', minutes: 45},
    B_V_3: {task: 'Research: Read 1 international paper on AI in cybercrime investigation', resource: 'Europol Innovation Lab reports — europol.europa.eu', minutes: 40},
    B_V_4: {task: 'Teach: Conduct a 30-min cybersecurity awareness session using AI examples', resource: 'Your own slides — Google Slides template', minutes: 45},
    C_B_0: {task: 'Try: Paste a 2-page document into ChatGPT — ask for a 5-point summary', resource: 'Any UP Police press release or circular', minutes: 20},
    C_B_1: {task: 'Practice: Use Google Translate + Whisper to transcribe a Hindi voice note to English text', resource: 'Google Translate app + OpenAI Whisper (free online)', minutes: 25},
    C_B_2: {task: "Learn: Watch 'Google Sheets for Beginners' — build a simple crime count tracker", resource: "YouTube: Kevin Stratvert 'Google Sheets Tutorial'", minutes: 40},
    C_B_3: {task: "Exercise: Analyse last month's FIR data — find the top 3 crime types by count", resource: 'Excel or Google Sheets with sample data provided', minutes: 30},
    C_B_4: {task: 'Draft: Use AI to write a sample press statement about a road safety campaign', resource: "ChatGPT with prompt: 'Write a formal press statement for...'", minutes: 25},
    C_I_0: {task: 'Build: Create a Google Sheet dashboard tracking weekly FIR counts by PS', resource: 'Google Sheets — COUNTIF + conditional formatting', minutes: 40},
    C_I_1: {task: 'Automate: Use ChatGPT to convert a handwritten note (photo) to structured text', resource: 'ChatGPT Vision / Google Lens + cleanup prompt', minutes: 30},
    C_I_2: {task: 'Practice: Write 3 different-style reports from the same data using AI', resource: 'ChatGPT — try formal, bullet-point, and narrative formats', minutes: 35},
    C_I_3: {task: 'Explore: Use AI to detect anomalies in a dataset (e.g. unusual spike in complaints)', resource: 'Google Sheets + ChatGPT data analysis', minutes: 35},
    C_I_4: {task: "Share: Create a 1-slide 'Data Story' from real crime trend data for your senior", resource: 'Google Slides — 1 chart + 3 key insights', minutes: 40},
    C_V_0: {task: 'Build: Design a monthly crime analytics report template using AI + Sheets', resource: 'Google Sheets + ChatGPT for narrative generation', minutes: 50},
    C_V_1: {task: 'Integrate: Set up an automated WhatsApp/email summary of daily crime data', resource: 'Google Sheets + Zapier free tier — no code needed', minutes: 45},
    C_V_2: {task: 'Lead: Train 3 colleagues on using AI for report drafting', resource: 'Internal session — create a reusable 1-page guide', minutes: 40},
    C_V_3: {task: 'Evaluate: Compare AI transcription tools for accuracy in Hindi/Hinglish', resource: 'Whisper, Google Speech-to-Text, Deepgram — test on 1 audio file', minutes: 40},
    C_V_4: {task: 'Contribute: Propose an AI-powered communication tool for your district', resource: 'Write a 1-page proposal — submit to IT/comms team', minutes: 45},
    D_B_0: {task: "Watch: 'How AI-powered CCTV works' — note how it differs from traditional cameras", resource: 'YouTube: Hikvision or Dahua AI CCTV explainer', minutes: 25},
    D_B_1: {task: 'Read: Facial recognition basics — how it works, key limitations', resource: 'Wikipedia: Facial recognition + NDTV article on India use', minutes: 25},
    D_B_2: {task: 'Explore: Find 1 case where AI CCTV helped solve a crime in India', resource: "Google News: 'facial recognition crime India 2023 2024'", minutes: 25},
    D_B_3: {task: "Learn: What is 'object detection' in AI? Watch a 10-min explainer", resource: "YouTube: '3Blue1Brown' or 'Computerphile' object detection", minutes: 25},
    D_B_4: {task: 'Reflect: List 3 locations in your area where AI CCTV could have the most impact', resource: 'Self-assessment — note in your 30-Day journal', minutes: 20},
    D_I_0: {task: 'Explore: Demo of AI CCTV — watch a vendor demo (Hikvision/Axis) and note features', resource: 'YouTube: Hikvision AI Demo + Axis Communications', minutes: 30},
    D_I_1: {task: "Read: Ethical guidelines on facial recognition — India's draft data protection bill", resource: 'meity.gov.in + AI ethics explainer on livemint.com', minutes: 35},
    D_I_2: {task: 'Analyse: Map 5 CCTV blind spots in your area + propose AI camera placement', resource: 'Google Maps + hand-drawn map — share with senior', minutes: 40},
    D_I_3: {task: 'Discuss: What are 3 legal/ethical boundaries your team must follow with AI surveillance?', resource: 'Team discussion + note key points in shared doc', minutes: 30},
    D_I_4: {task: 'Research: What is crowd analytics? Find 1 real use case from Indian smart city', resource: 'Smart Cities Mission website + Google News', minutes: 30},
    D_V_0: {task: 'Lead: Brief your unit on AI surveillance capabilities and legal boundaries', resource: 'Prepare 3-slide deck + case study example', minutes: 45},
    D_V_1: {task: 'Evaluate: Compare 3 AI CCTV vendors on price, accuracy, and compliance', resource: 'Request demos from Hikvision, Axis, Honeywell + create comparison sheet', minutes: 50},
    D_V_2: {task: 'Draft: Write a proposal for AI CCTV upgrade in 1 high-risk location', resource: '1-page proposal with problem, solution, cost estimate, impact', minutes: 45},
    D_V_3: {task: 'Contribute: Design a data governance SOP for CCTV footage in your unit', resource: 'Word/Google Docs — draft for review by legal/IT team', minutes: 45},
    D_V_4: {task: 'Teach: Conduct awareness session on deepfake video vs real footage detection', resource: 'InVID tool + real examples — 30-min team session', minutes: 40},
  }
};
