"""initial

Revision ID: 0877a8ef6869
Revises: 
Create Date: 2026-05-02 12:17:55.824226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0877a8ef6869'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('badge_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('officer_id', sa.String(length=36), nullable=False),
    sa.Column('score_a1', sa.Float(), nullable=False),
    sa.Column('score_a2', sa.Float(), nullable=False),
    sa.Column('score_a3', sa.Float(), nullable=False),
    sa.Column('score_a4', sa.Float(), nullable=False),
    sa.Column('score_a5', sa.Float(), nullable=False),
    sa.Column('score_b1', sa.Float(), nullable=False),
    sa.Column('score_b2', sa.Float(), nullable=False),
    sa.Column('score_b3', sa.Float(), nullable=False),
    sa.Column('score_b4', sa.Float(), nullable=False),
    sa.Column('score_b5', sa.Float(), nullable=False),
    sa.Column('score_c1', sa.Float(), nullable=False),
    sa.Column('score_c2', sa.Float(), nullable=False),
    sa.Column('score_c3', sa.Float(), nullable=False),
    sa.Column('score_c4', sa.Float(), nullable=False),
    sa.Column('score_c5', sa.Float(), nullable=False),
    sa.Column('score_d1', sa.Float(), nullable=False),
    sa.Column('score_d2', sa.Float(), nullable=False),
    sa.Column('score_d3', sa.Float(), nullable=False),
    sa.Column('score_d4', sa.Float(), nullable=False),
    sa.Column('score_d5', sa.Float(), nullable=False),
    sa.Column('avg_a', sa.Float(), nullable=False),
    sa.Column('avg_b', sa.Float(), nullable=False),
    sa.Column('avg_c', sa.Float(), nullable=False),
    sa.Column('avg_d', sa.Float(), nullable=False),
    sa.Column('avg_overall', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('officer_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officer_id'),
    sa.UniqueConstraint('officer_id')
    )
    op.create_table('plan_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('focus_area', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('task_key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_days')
    op.drop_table('learning_plans')
    op.drop_table('assessments')
    op.drop_table('officers')
    # ### end Alembic commands ###
