"""add_analyst_tables

Revision ID: 618f82607281
Revises: 0001
Create Date: 2026-06-26 20:59:18.069405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618f82607281'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_names', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('runs', sa.Column('session_id', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('dataset_id', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('answer_text', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('table_json', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('chart_b64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'chart_b64')
    op.drop_column('runs', 'table_json')
    op.drop_column('runs', 'answer_text')
    op.drop_column('runs', 'question')
    op.drop_column('runs', 'dataset_id')
    op.drop_column('runs', 'session_id')
    op.drop_table('sessions')
    op.drop_table('datasets')
    # ### end Alembic commands ###
