"""add_contacts_json_to_leads

Revision ID: abd80844d137
Revises: abe038cd88bd
Create Date: 2026-04-24 16:24:09.540913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd80844d137'
down_revision: Union[str, None] = 'abe038cd88bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('contacts_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'contacts_json')
    # ### end Alembic commands ###
