"""initial

Revision ID: abe038cd88bd
Revises: 
Create Date: 2026-04-24 15:57:12.087354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe038cd88bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('size_min', sa.Integer(), nullable=True),
    sa.Column('size_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('lead_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_run_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('headcount_estimate', sa.String(length=50), nullable=True),
    sa.Column('why_fit', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_domain', 'leads', ['domain'], unique=True)
    op.create_index('ix_leads_search_run_id', 'leads', ['search_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_search_run_id', table_name='leads')
    op.drop_index('ix_leads_domain', table_name='leads')
    op.drop_table('leads')
    op.drop_table('search_runs')
    # ### end Alembic commands ###
