"""initial

Revision ID: ba88f74aeae7
Revises: 
Create Date: 2026-04-24 04:07:03.040316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba88f74aeae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_logs')
    # ### end Alembic commands ###
