import json
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Float, Index, Integer, JSON, Text, TIMESTAMP, func, text, type_coerce
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _uuid() -> str:
    """Return a new random UUID string for use as a primary-key default."""
    return str(uuid4())


def _now() -> datetime:
    """Return the current time as a timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


def _loads(raw: str | None, default):
    """Decode JSON ``raw`` or return ``default`` when unset."""
    return json.loads(raw) if raw else default


def input_schema_from_parameters(parameters: list[dict]) -> dict:
    """Derive an MCP ``inputSchema`` object from a tool's execution ``parameters`` list.

    Each parameter is ``{"name", "type", "description?", "required?"}``; the derived schema is the
    standard ``{"type": "object", "properties": {...}, "required": [...]}`` MCP clients expect.
    """
    props: dict = {}
    required: list[str] = []
    for p in parameters or []:
        name = p.get("name")
        if not name:
            continue
        prop: dict = {"type": p.get("type") or "string"}
        if p.get("description"):
            prop["description"] = p["description"]
        props[name] = prop
        if p.get("required"):
            required.append(name)
    schema: dict = {"type": "object", "properties": props}
    if required:
        schema["required"] = required
    return schema


class Base(DeclarativeBase):
    pass


class DatabaseRow(Base):
    """A **database** — an instance of an MCP server *type* (``type``: parquet, postgresql, …), backed
    1:1 by a dataset URI. Each type's connector logic + behaviour lives in code (``tools/connectors/``).

    Per the MCP spec a database (served as an MCP server) has three kinds of children — tools, resources,
    prompts — generated by the sync pipeline and stored as rows. The dataset itself is not a separate
    entity: only its URI + type are metadata on this row; its **physical tables are inspected live by
    the connector** (no stored catalog). The dataset's per-table columns live on the entity resources and
    its entity-relationship schema on the ``kind='schema'`` resource (the source of truth). ``name`` and
    ``uri`` are unique (the 1:1 dataset↔database constraint).
    """

    __tablename__ = "databases"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    type: Mapped[str] = mapped_column(Text, nullable=False, default="parquet")  # MCP server type
    uri: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    last_synced_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    last_sync_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    connection_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )


class _CapabilityMixin:
    """Shared versioning + soft-delete envelope for tool/resource/prompt child rows.

    Capabilities are NEVER hard-deleted by sync or the dispatcher: a removal sets ``deleted_at`` +
    ``deleted_version``. The "active" view is ``database_id = ? AND deleted_at IS NULL``.
    """

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    database_id: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    created_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    deleted_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    deleted_version: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class McpToolRow(_CapabilityMixin, Base):
    """A canned "GET-API" MCP tool: a parameterized read-only SELECT over the server's tables.

    All tool metadata is stored in a single ``meta_json`` column::

        {"execution":     {"sql_template": "SELECT … WHERE x > $min",
                           "parameters":   [{"name": "min", "type": "integer", ...}]},
         "input_schema":  {"type": "object", "properties": {...}, "required": [...]},
         "output_schema": {},
         "annotations":   {}}
    """

    __tablename__ = "mcp_tools"
    __table_args__ = (
        Index(
            "uq_mcp_tools_active_name",
            "database_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    meta_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")

    def _meta(self) -> dict:
        return _loads(self.meta_json, {})

    def _set_meta_key(self, key: str, value) -> None:
        m = self._meta()
        m[key] = value
        self.meta_json = json.dumps(m)

    @property
    def execution(self) -> dict:
        """The executor spec: ``{"sql_template": str, "parameters": [{"name","type",...}]}``."""
        return self._meta().get("execution") or {}

    @execution.setter
    def execution(self, value: dict) -> None:
        self._set_meta_key("execution", value or {})

    @property
    def parameters(self) -> list[dict]:
        """The declared ``$param`` embeddings: ``[{"name","type","description?","required?"}]``."""
        return (self.execution or {}).get("parameters") or []

    @property
    def sql_template(self) -> str:
        """The SQL template (with ``$param`` embeddings), derived from ``execution``."""
        return (self.execution or {}).get("sql_template") or ""

    @property
    def input_schema(self) -> dict:
        """MCP ``inputSchema`` — stored in meta or derived from execution parameters."""
        stored = self._meta().get("input_schema")
        if stored:
            return stored
        return input_schema_from_parameters(self.parameters)

    @input_schema.setter
    def input_schema(self, value: dict) -> None:
        self._set_meta_key("input_schema", value or {})

    @property
    def output_schema(self) -> dict | None:
        return self._meta().get("output_schema") or None

    @output_schema.setter
    def output_schema(self, value: dict | None) -> None:
        self._set_meta_key("output_schema", value or {})

    @property
    def annotations(self) -> dict | None:
        return self._meta().get("annotations") or None

    @annotations.setter
    def annotations(self, value: dict | None) -> None:
        self._set_meta_key("annotations", value or {})

    # ── backward-compat aliases (old column names → meta_json) ──────────────
    @property
    def execution_json(self) -> str:
        return json.dumps(self.execution)

    @execution_json.setter
    def execution_json(self, value: str | None) -> None:
        self._set_meta_key("execution", json.loads(value) if value else {})

    @property
    def output_schema_json(self) -> str | None:
        v = self._meta().get("output_schema")
        return json.dumps(v) if v is not None else None

    @output_schema_json.setter
    def output_schema_json(self, value: str | None) -> None:
        self._set_meta_key("output_schema", json.loads(value) if value else None)

    @property
    def annotations_json(self) -> str | None:
        v = self._meta().get("annotations")
        return json.dumps(v) if v is not None else None

    @annotations_json.setter
    def annotations_json(self, value: str | None) -> None:
        self._set_meta_key("annotations", json.loads(value) if value else None)


class McpResourceRow(_CapabilityMixin, Base):
    """An MCP resource: the dataset schema, or a primary/secondary entity derived from it.

    ``content_json`` stores all content including the resource kind::

        {"kind": "primary_entity", ...entity-specific fields...}
    """

    __tablename__ = "mcp_resources"
    __table_args__ = (
        Index(
            "uq_mcp_resources_active_uri",
            "uri",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    uri: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    mime_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    content_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    size: Mapped[int | None] = mapped_column(Integer, nullable=True)  # bytes: parquet file (table) or content_json (schema)

    @hybrid_property
    def kind(self) -> str:
        return (self.content or {}).get("kind") or "primary_entity"

    @kind.setter
    def kind(self, value: str) -> None:
        c = _loads(self.content_json, {}) or {}
        c["kind"] = value
        self.content_json = json.dumps(c)

    @kind.expression
    @classmethod
    def kind(cls):
        # type_coerce (no SQL CAST emitted) lets SQLAlchemy use JSON subscript semantics:
        # json_extract(col, '$.kind') on SQLite, col->>'kind' on PostgreSQL.
        return func.coalesce(type_coerce(cls.content_json, JSON)["kind"].as_string(), "primary_entity")

    @property
    def content(self):
        return _loads(self.content_json, None)

    @content.setter
    def content(self, value) -> None:
        if value is not None:
            existing = _loads(self.content_json, {}) or {}
            if "kind" in existing and "kind" not in value:
                value = {"kind": existing["kind"], **value}
        self.content_json = json.dumps(value)


class McpPromptRow(_CapabilityMixin, Base):
    """An MCP prompt template over the server's tools.

    ``meta_json`` stores both the argument spec and the template::

        {"arguments": [{"name": "...", "description": "...", "required": true}],
         "template":   {...}}
    """

    __tablename__ = "mcp_prompts"
    __table_args__ = (
        Index(
            "uq_mcp_prompts_active_name",
            "database_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    meta_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    def _meta(self) -> dict:
        return _loads(self.meta_json, {})

    @property
    def arguments(self) -> list[dict]:
        return self._meta().get("arguments") or []

    @arguments.setter
    def arguments(self, value: list[dict]) -> None:
        m = self._meta()
        m["arguments"] = value or []
        self.meta_json = json.dumps(m)

    @property
    def template(self):
        return self._meta().get("template")

    @template.setter
    def template(self, value) -> None:
        m = self._meta()
        m["template"] = value
        self.meta_json = json.dumps(m)

    # ── backward-compat aliases (old column names → meta_json) ──────────────
    @property
    def arguments_json(self) -> str | None:
        v = self._meta().get("arguments")
        return json.dumps(v) if v is not None else None

    @arguments_json.setter
    def arguments_json(self, value: str | None) -> None:
        m = self._meta()
        m["arguments"] = json.loads(value) if value else []
        self.meta_json = json.dumps(m)

    @property
    def template_json(self) -> str | None:
        v = self._meta().get("template")
        return json.dumps(v) if v is not None else None

    @template_json.setter
    def template_json(self, value: str | None) -> None:
        m = self._meta()
        m["template"] = json.loads(value) if value is not None else None
        self.meta_json = json.dumps(m)


class SessionRow(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class SessionDatabaseRow(Base):
    """Join table linking a session to the MCP servers it spans (many-to-many)."""

    __tablename__ = "session_databases"

    session_id: Mapped[str] = mapped_column(Text, primary_key=True)
    database_id: Mapped[str] = mapped_column(Text, primary_key=True)


class QueryRecordRow(Base):
    __tablename__ = "query_records"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    session_id: Mapped[str] = mapped_column(Text, nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    iteration_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    query_history_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    api_request_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )

    @property
    def query_history(self) -> list[dict]:
        """Decode the tool-call trace: [{tool, arguments, result, is_error, capability?}]."""
        return _loads(self.query_history_json, [])


class AgentRunRow(Base):
    __tablename__ = "agent_runs"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    query_record_id: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )
