import datetime
import json

import pytest

from travel_itinerary.domain.models import Dish, HotelInfo, HotelSearchParams, HotelSearchResult, ItineraryResponse, Place
from travel_itinerary.llm.client import LLMClient, _booking_url, _booking_url_full
from travel_itinerary.llm.providers import StubProvider


def _default_params(**overrides) -> HotelSearchParams:
    base = dict(
        city="Paris",
        checkin=datetime.date(2026, 6, 1),
        checkout=datetime.date(2026, 6, 5),
        guests=2,
        budget_min=80,
        budget_max=150,
        star_rating=3,
    )
    base.update(overrides)
    return HotelSearchParams(**base)


def test_stub_provider_returns_valid_json():
    provider = StubProvider()
    raw = provider.call("any prompt")
    data = json.loads(raw)
    assert "places" in data
    assert "dish" in data
    assert "hotel" in data
    assert len(data["places"]) == 3


def test_stub_provider_hotel_search():
    provider = StubProvider()
    raw = provider.call("<hotel_search> dummy </hotel_search>")
    data = json.loads(raw)
    assert "hotels" in data
    assert len(data["hotels"]) == 3
    for h in data["hotels"]:
        assert h["name"]
        assert h["amenities"]


def test_llm_client_stub_is_flagged():
    client = LLMClient(StubProvider())
    assert client.is_stub is True


def test_llm_client_get_itinerary_returns_response():
    client = LLMClient(StubProvider())
    result = client.get_itinerary("Paris")
    assert isinstance(result, ItineraryResponse)
    assert result.city == "Paris"
    assert len(result.places) == 3
    assert isinstance(result.dish, Dish)
    assert isinstance(result.hotel, HotelInfo)
    for place in result.places:
        assert place.name
        assert place.description
        assert place.tips


def test_llm_client_search_hotels_returns_result():
    client = LLMClient(StubProvider())
    params = _default_params()
    result = client.search_hotels(params)
    assert isinstance(result, HotelSearchResult)
    assert result.city == "Paris"
    assert len(result.hotels) == 3
    for hotel in result.hotels:
        assert hotel.name
        assert hotel.description
        assert hotel.amenities
        assert hotel.estimated_price
        assert "booking.com" in hotel.booking_url


def test_hotel_booking_url_injected_by_client():
    """Booking URL must be generated by the client, not the LLM."""
    client = LLMClient(StubProvider())
    result = client.get_itinerary("Tokyo")
    assert "booking.com" in result.hotel.booking_url
    assert "Tokyo" in result.hotel.booking_url
    assert "class" in result.hotel.booking_url


def test_hotel_search_url_contains_all_params():
    client = LLMClient(StubProvider())
    params = _default_params(city="Tokyo", star_rating=4, budget_min=100, budget_max=200)
    result = client.search_hotels(params)
    url = result.hotels[0].booking_url
    assert "Tokyo" in url
    assert "2026-06-01" in url
    assert "2026-06-05" in url
    assert "class%3D4" in url or "class=4" in url


def test_booking_url_helper():
    url = _booking_url("New York")
    assert url.startswith("https://www.booking.com")
    assert "New+York" in url or "New%20York" in url
    assert "class" in url


def test_booking_url_full_helper():
    params = _default_params()
    url = _booking_url_full(params)
    assert "booking.com" in url
    assert "Paris" in url
    assert "2026-06-01" in url
    assert "group_adults" in url


def test_llm_client_strips_markdown_fences():
    """Client must strip ```json ... ``` wrappers from LLM output."""

    class MarkdownWrappedProvider(StubProvider):
        def call(self, prompt: str) -> str:
            return "```json\n" + super().call(prompt) + "\n```"

    client = LLMClient(MarkdownWrappedProvider())
    result = client.get_itinerary("Tokyo")
    assert isinstance(result, ItineraryResponse)


def test_create_client_returns_stub_when_no_key(monkeypatch):
    from travel_itinerary.config import settings as settings_module
    from travel_itinerary.llm.client import create_client

    settings_module.get_settings.cache_clear()
    monkeypatch.setenv("GOOGLE_API_KEY", "")
    client = create_client()
    assert client.is_stub is True
    settings_module.get_settings.cache_clear()

